# Site settings
name: Satoshi In Valley
email: 
author: Satoshi Zhang
url: http://www.hifreud.com
resume_site: http://www.hifreud.com
github: http://www.hifreud.com
baseurl: "/myProject"
description: 做时间的朋友!
meta_description: 
motto: 做时间的朋友.
banner:

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
location: "/comments"

